### ISSUE TITLE
"ValueError: Empty value passed for a required argument" during setup

### ISSUE THREAD

**Issue by remram44** [inveniosoftware/invenio-search#152]
Might be related to #149, however it happens with `elasticsearch-dsl<6.2`, even with Elasticsearch 5 (with `elasticsearch==5.5.3` and `elasticsearch-dsl==5.4.0`).

```
Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/invenio", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/invenio_search/cli.py", line 44, in inner
    return f(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/invenio_search/cli.py", line 97, in destroy
    for name, response in bar:
  File "/home/ubuntu/venv/lib/python3.6/site-packages/click/_termui_impl.py", line 285, in generator
    for rv in self.iter:
  File "/home/ubuntu/venv/lib/python3.6/site-packages/invenio_search/ext.py", line 309, in delete
    for result in _delete(self.active_aliases):
  File "/home/ubuntu/venv/lib/python3.6/site-packages/invenio_search/ext.py", line 301, in _delete
    for result in _delete(value, alias=name):
  File "/home/ubuntu/venv/lib/python3.6/site-packages/invenio_search/ext.py", line 295, in _delete
    ignore=ignore,
  File "/home/ubuntu/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/ubuntu/venv/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 432, in delete_alias
    raise ValueError("Empty value passed for a required argument.")
ValueError: Empty value passed for a required argument.
```

**Comment by rjuppa** [comment]
How difficult would be to print it out the name of the empty field?
